kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.port }}
    targetPort: {{ .Values.deployment.port }}